ListenPort: 8080
MaxRequestBodySize: 100000000
Service:
  RailgunCDN:
    COS:
      Region: "ap-shanghai"
      Bucket: "example-1300000000"
      SecretID: "AKIDxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      SecretKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    CDN:
      Domain: "https://cdn.example.com"
      PKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    Tenants:
      - RootPath: "app-a"
        AppID: "app-a"
        AppKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"